version: '3.3'

services:
  db:
    image: postgres:16.0-alpine
    restart: always
    volumes:
      - postgres_value:/var/lib/postgresql/data/
    env_file:
      - ./journal/.env

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    volumes:
      - pgadmin_value:/var/lib/pgadmin/data/
    ports:
      - "5050:80"
    env_file:
      - ./journal/.env

  web:
    build: .
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./journal/.env

  nginx:
    image: nginx:1.25.2-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web

volumes:
  postgres_value:
  pgadmin_value:
  static_value:
  media_value:
