# Generated by Django 4.2.5 on 2023-09-21 22:48

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Введите текст поста', verbose_name='текст поста'),
        ),
    ]
